//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.05 at 04:19:31 PM EET 
//


package mypackage;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mypackage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RecipesRecipeCommentOrderid_QNAME = new QName("", "orderid");
    private final static QName _RecipesRecipeCommentName_QNAME = new QName("", "name");
    private final static QName _RecipesRecipeCommentShipdate_QNAME = new QName("", "shipdate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mypackage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Recipes }
     * 
     */
    public Recipes createRecipes() {
        return new Recipes();
    }

    /**
     * Create an instance of {@link Recipes.Recipe }
     * 
     */
    public Recipes.Recipe createRecipesRecipe() {
        return new Recipes.Recipe();
    }

    /**
     * Create an instance of {@link Recipes.Recipe.Ingredients }
     * 
     */
    public Recipes.Recipe.Ingredients createRecipesRecipeIngredients() {
        return new Recipes.Recipe.Ingredients();
    }

    /**
     * Create an instance of {@link Recipes.Recipe.Preparation }
     * 
     */
    public Recipes.Recipe.Preparation createRecipesRecipePreparation() {
        return new Recipes.Recipe.Preparation();
    }

    /**
     * Create an instance of {@link Recipes.Recipe.Comment }
     * 
     */
    public Recipes.Recipe.Comment createRecipesRecipeComment() {
        return new Recipes.Recipe.Comment();
    }

    /**
     * Create an instance of {@link Recipes.Recipe.Nutrients }
     * 
     */
    public Recipes.Recipe.Nutrients createRecipesRecipeNutrients() {
        return new Recipes.Recipe.Nutrients();
    }

    /**
     * Create an instance of {@link Recipes.Recipe.Ingredients.Ingredient }
     * 
     */
    public Recipes.Recipe.Ingredients.Ingredient createRecipesRecipeIngredientsIngredient() {
        return new Recipes.Recipe.Ingredients.Ingredient();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "orderid", scope = Recipes.Recipe.Comment.class)
    public JAXBElement<BigInteger> createRecipesRecipeCommentOrderid(BigInteger value) {
        return new JAXBElement<BigInteger>(_RecipesRecipeCommentOrderid_QNAME, BigInteger.class, Recipes.Recipe.Comment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name", scope = Recipes.Recipe.Comment.class)
    public JAXBElement<String> createRecipesRecipeCommentName(String value) {
        return new JAXBElement<String>(_RecipesRecipeCommentName_QNAME, String.class, Recipes.Recipe.Comment.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shipdate", scope = Recipes.Recipe.Comment.class)
    public JAXBElement<XMLGregorianCalendar> createRecipesRecipeCommentShipdate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RecipesRecipeCommentShipdate_QNAME, XMLGregorianCalendar.class, Recipes.Recipe.Comment.class, value);
    }

}
